//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./live-monitoring_types');
//HELPER FUNCTIONS AND STRUCTURES

StatisticsService_queryTimeSeries_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.QueryTimeSeriesRequest(args.request);
    }
  }
};
StatisticsService_queryTimeSeries_args.prototype = {};
StatisticsService_queryTimeSeries_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.QueryTimeSeriesRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatisticsService_queryTimeSeries_args.prototype.write = function(output) {
  output.writeStructBegin('StatisticsService_queryTimeSeries_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatisticsService_queryTimeSeries_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.QueryTimeSeriesResponse(args.success);
    }
  }
};
StatisticsService_queryTimeSeries_result.prototype = {};
StatisticsService_queryTimeSeries_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.QueryTimeSeriesResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatisticsService_queryTimeSeries_result.prototype.write = function(output) {
  output.writeStructBegin('StatisticsService_queryTimeSeries_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatisticsService_putTimeSeries_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.PutTimeSeriesRequest(args.request);
    }
  }
};
StatisticsService_putTimeSeries_args.prototype = {};
StatisticsService_putTimeSeries_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.PutTimeSeriesRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatisticsService_putTimeSeries_args.prototype.write = function(output) {
  output.writeStructBegin('StatisticsService_putTimeSeries_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatisticsService_putTimeSeries_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.PutTimeSeriesResponse(args.success);
    }
  }
};
StatisticsService_putTimeSeries_result.prototype = {};
StatisticsService_putTimeSeries_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.PutTimeSeriesResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatisticsService_putTimeSeries_result.prototype.write = function(output) {
  output.writeStructBegin('StatisticsService_putTimeSeries_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatisticsServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
StatisticsServiceClient.prototype = {};
StatisticsServiceClient.prototype.seqid = function() { return this._seqid; }
StatisticsServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
StatisticsServiceClient.prototype.queryTimeSeries = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_queryTimeSeries(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_queryTimeSeries(request);
  }
};

StatisticsServiceClient.prototype.send_queryTimeSeries = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('queryTimeSeries', Thrift.MessageType.CALL, this.seqid());
  var args = new StatisticsService_queryTimeSeries_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StatisticsServiceClient.prototype.recv_queryTimeSeries = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StatisticsService_queryTimeSeries_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('queryTimeSeries failed: unknown result');
};
StatisticsServiceClient.prototype.putTimeSeries = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_putTimeSeries(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_putTimeSeries(request);
  }
};

StatisticsServiceClient.prototype.send_putTimeSeries = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('putTimeSeries', Thrift.MessageType.CALL, this.seqid());
  var args = new StatisticsService_putTimeSeries_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StatisticsServiceClient.prototype.recv_putTimeSeries = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StatisticsService_putTimeSeries_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('putTimeSeries failed: unknown result');
};
StatisticsServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
StatisticsServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

StatisticsServiceProcessor.prototype.process_queryTimeSeries = function(seqid, input, output) {
  var args = new StatisticsService_queryTimeSeries_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.queryTimeSeries.length === 1) {
    Q.fcall(this._handler.queryTimeSeries, args.request)
      .then(function(result) {
        var result = new StatisticsService_queryTimeSeries_result({success: result});
        output.writeMessageBegin("queryTimeSeries", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("queryTimeSeries", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.queryTimeSeries(args.request, function (err, result) {
      if (err == null) {
        var result = new StatisticsService_queryTimeSeries_result((err != null ? err : {success: result}));
        output.writeMessageBegin("queryTimeSeries", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("queryTimeSeries", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

StatisticsServiceProcessor.prototype.process_putTimeSeries = function(seqid, input, output) {
  var args = new StatisticsService_putTimeSeries_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.putTimeSeries.length === 1) {
    Q.fcall(this._handler.putTimeSeries, args.request)
      .then(function(result) {
        var result = new StatisticsService_putTimeSeries_result({success: result});
        output.writeMessageBegin("putTimeSeries", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("putTimeSeries", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.putTimeSeries(args.request, function (err, result) {
      if (err == null) {
        var result = new StatisticsService_putTimeSeries_result((err != null ? err : {success: result}));
        output.writeMessageBegin("putTimeSeries", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("putTimeSeries", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

