//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./billing_usage_types');
//HELPER FUNCTIONS AND STRUCTURES

var UsageService_ping_args = function(args) {
  this.str = null;
  if (args) {
    if (args.str !== undefined && args.str !== null) {
      this.str = args.str;
    }
  }
};
UsageService_ping_args.prototype = {};
UsageService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.str = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('UsageService_ping_args');
  if (this.str !== null && this.str !== undefined) {
    output.writeFieldBegin('str', Thrift.Type.I32, 1);
    output.writeI32(this.str);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
UsageService_ping_result.prototype = {};
UsageService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('UsageService_ping_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByVendor_args = function(args) {
  this.vid = null;
  this.skus = null;
  this.fromTs = null;
  this.toTs = null;
  this.interval = null;
  if (args) {
    if (args.vid !== undefined && args.vid !== null) {
      this.vid = args.vid;
    }
    if (args.skus !== undefined && args.skus !== null) {
      this.skus = Thrift.copyList(args.skus, [null]);
    }
    if (args.fromTs !== undefined && args.fromTs !== null) {
      this.fromTs = args.fromTs;
    }
    if (args.toTs !== undefined && args.toTs !== null) {
      this.toTs = args.toTs;
    }
    if (args.interval !== undefined && args.interval !== null) {
      this.interval = args.interval;
    }
  }
};
UsageService_getUsageByVendor_args.prototype = {};
UsageService_getUsageByVendor_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.vid = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size18 = 0;
        var _rtmp322;
        this.skus = [];
        var _etype21 = 0;
        _rtmp322 = input.readListBegin();
        _etype21 = _rtmp322.etype;
        _size18 = _rtmp322.size;
        for (var _i23 = 0; _i23 < _size18; ++_i23)
        {
          var elem24 = null;
          elem24 = input.readI32();
          this.skus.push(elem24);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.fromTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.toTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.interval = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByVendor_args.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByVendor_args');
  if (this.vid !== null && this.vid !== undefined) {
    output.writeFieldBegin('vid', Thrift.Type.I32, 1);
    output.writeI32(this.vid);
    output.writeFieldEnd();
  }
  if (this.skus !== null && this.skus !== undefined) {
    output.writeFieldBegin('skus', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.I32, this.skus.length);
    for (var iter25 in this.skus)
    {
      if (this.skus.hasOwnProperty(iter25))
      {
        iter25 = this.skus[iter25];
        output.writeI32(iter25);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.fromTs !== null && this.fromTs !== undefined) {
    output.writeFieldBegin('fromTs', Thrift.Type.I32, 3);
    output.writeI32(this.fromTs);
    output.writeFieldEnd();
  }
  if (this.toTs !== null && this.toTs !== undefined) {
    output.writeFieldBegin('toTs', Thrift.Type.I32, 4);
    output.writeI32(this.toTs);
    output.writeFieldEnd();
  }
  if (this.interval !== null && this.interval !== undefined) {
    output.writeFieldBegin('interval', Thrift.Type.I32, 5);
    output.writeI32(this.interval);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByVendor_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.UsageItem]);
    }
  }
};
UsageService_getUsageByVendor_result.prototype = {};
UsageService_getUsageByVendor_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size26 = 0;
        var _rtmp330;
        this.success = [];
        var _etype29 = 0;
        _rtmp330 = input.readListBegin();
        _etype29 = _rtmp330.etype;
        _size26 = _rtmp330.size;
        for (var _i31 = 0; _i31 < _size26; ++_i31)
        {
          var elem32 = null;
          elem32 = new ttypes.UsageItem();
          elem32.read(input);
          this.success.push(elem32);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByVendor_result.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByVendor_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter33 in this.success)
    {
      if (this.success.hasOwnProperty(iter33))
      {
        iter33 = this.success[iter33];
        iter33.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByVendorList_args = function(args) {
  this.vids = null;
  this.skus = null;
  this.fromTs = null;
  this.toTs = null;
  this.interval = null;
  if (args) {
    if (args.vids !== undefined && args.vids !== null) {
      this.vids = Thrift.copyList(args.vids, [null]);
    }
    if (args.skus !== undefined && args.skus !== null) {
      this.skus = Thrift.copyList(args.skus, [null]);
    }
    if (args.fromTs !== undefined && args.fromTs !== null) {
      this.fromTs = args.fromTs;
    }
    if (args.toTs !== undefined && args.toTs !== null) {
      this.toTs = args.toTs;
    }
    if (args.interval !== undefined && args.interval !== null) {
      this.interval = args.interval;
    }
  }
};
UsageService_getUsageByVendorList_args.prototype = {};
UsageService_getUsageByVendorList_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size34 = 0;
        var _rtmp338;
        this.vids = [];
        var _etype37 = 0;
        _rtmp338 = input.readListBegin();
        _etype37 = _rtmp338.etype;
        _size34 = _rtmp338.size;
        for (var _i39 = 0; _i39 < _size34; ++_i39)
        {
          var elem40 = null;
          elem40 = input.readI32();
          this.vids.push(elem40);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size41 = 0;
        var _rtmp345;
        this.skus = [];
        var _etype44 = 0;
        _rtmp345 = input.readListBegin();
        _etype44 = _rtmp345.etype;
        _size41 = _rtmp345.size;
        for (var _i46 = 0; _i46 < _size41; ++_i46)
        {
          var elem47 = null;
          elem47 = input.readI32();
          this.skus.push(elem47);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.fromTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.toTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.interval = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByVendorList_args.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByVendorList_args');
  if (this.vids !== null && this.vids !== undefined) {
    output.writeFieldBegin('vids', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.vids.length);
    for (var iter48 in this.vids)
    {
      if (this.vids.hasOwnProperty(iter48))
      {
        iter48 = this.vids[iter48];
        output.writeI32(iter48);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.skus !== null && this.skus !== undefined) {
    output.writeFieldBegin('skus', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.I32, this.skus.length);
    for (var iter49 in this.skus)
    {
      if (this.skus.hasOwnProperty(iter49))
      {
        iter49 = this.skus[iter49];
        output.writeI32(iter49);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.fromTs !== null && this.fromTs !== undefined) {
    output.writeFieldBegin('fromTs', Thrift.Type.I32, 3);
    output.writeI32(this.fromTs);
    output.writeFieldEnd();
  }
  if (this.toTs !== null && this.toTs !== undefined) {
    output.writeFieldBegin('toTs', Thrift.Type.I32, 4);
    output.writeI32(this.toTs);
    output.writeFieldEnd();
  }
  if (this.interval !== null && this.interval !== undefined) {
    output.writeFieldBegin('interval', Thrift.Type.I32, 5);
    output.writeI32(this.interval);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByVendorList_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.UsageItem]);
    }
  }
};
UsageService_getUsageByVendorList_result.prototype = {};
UsageService_getUsageByVendorList_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size50 = 0;
        var _rtmp354;
        this.success = [];
        var _etype53 = 0;
        _rtmp354 = input.readListBegin();
        _etype53 = _rtmp354.etype;
        _size50 = _rtmp354.size;
        for (var _i55 = 0; _i55 < _size50; ++_i55)
        {
          var elem56 = null;
          elem56 = new ttypes.UsageItem();
          elem56.read(input);
          this.success.push(elem56);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByVendorList_result.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByVendorList_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter57 in this.success)
    {
      if (this.success.hasOwnProperty(iter57))
      {
        iter57 = this.success[iter57];
        iter57.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByGroup_args = function(args) {
  this.vids = null;
  this.skus = null;
  this.fromTs = null;
  this.toTs = null;
  this.interval = null;
  if (args) {
    if (args.vids !== undefined && args.vids !== null) {
      this.vids = Thrift.copyList(args.vids, [null]);
    }
    if (args.skus !== undefined && args.skus !== null) {
      this.skus = Thrift.copyList(args.skus, [null]);
    }
    if (args.fromTs !== undefined && args.fromTs !== null) {
      this.fromTs = args.fromTs;
    }
    if (args.toTs !== undefined && args.toTs !== null) {
      this.toTs = args.toTs;
    }
    if (args.interval !== undefined && args.interval !== null) {
      this.interval = args.interval;
    }
  }
};
UsageService_getUsageByGroup_args.prototype = {};
UsageService_getUsageByGroup_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size58 = 0;
        var _rtmp362;
        this.vids = [];
        var _etype61 = 0;
        _rtmp362 = input.readListBegin();
        _etype61 = _rtmp362.etype;
        _size58 = _rtmp362.size;
        for (var _i63 = 0; _i63 < _size58; ++_i63)
        {
          var elem64 = null;
          elem64 = input.readI32();
          this.vids.push(elem64);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size65 = 0;
        var _rtmp369;
        this.skus = [];
        var _etype68 = 0;
        _rtmp369 = input.readListBegin();
        _etype68 = _rtmp369.etype;
        _size65 = _rtmp369.size;
        for (var _i70 = 0; _i70 < _size65; ++_i70)
        {
          var elem71 = null;
          elem71 = input.readI32();
          this.skus.push(elem71);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.fromTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.toTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.interval = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByGroup_args.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByGroup_args');
  if (this.vids !== null && this.vids !== undefined) {
    output.writeFieldBegin('vids', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.vids.length);
    for (var iter72 in this.vids)
    {
      if (this.vids.hasOwnProperty(iter72))
      {
        iter72 = this.vids[iter72];
        output.writeI32(iter72);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.skus !== null && this.skus !== undefined) {
    output.writeFieldBegin('skus', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.I32, this.skus.length);
    for (var iter73 in this.skus)
    {
      if (this.skus.hasOwnProperty(iter73))
      {
        iter73 = this.skus[iter73];
        output.writeI32(iter73);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.fromTs !== null && this.fromTs !== undefined) {
    output.writeFieldBegin('fromTs', Thrift.Type.I32, 3);
    output.writeI32(this.fromTs);
    output.writeFieldEnd();
  }
  if (this.toTs !== null && this.toTs !== undefined) {
    output.writeFieldBegin('toTs', Thrift.Type.I32, 4);
    output.writeI32(this.toTs);
    output.writeFieldEnd();
  }
  if (this.interval !== null && this.interval !== undefined) {
    output.writeFieldBegin('interval', Thrift.Type.I32, 5);
    output.writeI32(this.interval);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByGroup_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.UsageItem]);
    }
  }
};
UsageService_getUsageByGroup_result.prototype = {};
UsageService_getUsageByGroup_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size74 = 0;
        var _rtmp378;
        this.success = [];
        var _etype77 = 0;
        _rtmp378 = input.readListBegin();
        _etype77 = _rtmp378.etype;
        _size74 = _rtmp378.size;
        for (var _i79 = 0; _i79 < _size74; ++_i79)
        {
          var elem80 = null;
          elem80 = new ttypes.UsageItem();
          elem80.read(input);
          this.success.push(elem80);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByGroup_result.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByGroup_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter81 in this.success)
    {
      if (this.success.hasOwnProperty(iter81))
      {
        iter81 = this.success[iter81];
        iter81.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByRank_args = function(args) {
  this.skus = null;
  this.skuRank = null;
  this.isDescend = null;
  this.minVaue = null;
  this.maxValue = null;
  this.fromTs = null;
  this.toTs = null;
  this.interval = null;
  this.offset = null;
  this.limit = null;
  if (args) {
    if (args.skus !== undefined && args.skus !== null) {
      this.skus = Thrift.copyList(args.skus, [null]);
    }
    if (args.skuRank !== undefined && args.skuRank !== null) {
      this.skuRank = args.skuRank;
    }
    if (args.isDescend !== undefined && args.isDescend !== null) {
      this.isDescend = args.isDescend;
    }
    if (args.minVaue !== undefined && args.minVaue !== null) {
      this.minVaue = args.minVaue;
    }
    if (args.maxValue !== undefined && args.maxValue !== null) {
      this.maxValue = args.maxValue;
    }
    if (args.fromTs !== undefined && args.fromTs !== null) {
      this.fromTs = args.fromTs;
    }
    if (args.toTs !== undefined && args.toTs !== null) {
      this.toTs = args.toTs;
    }
    if (args.interval !== undefined && args.interval !== null) {
      this.interval = args.interval;
    }
    if (args.offset !== undefined && args.offset !== null) {
      this.offset = args.offset;
    }
    if (args.limit !== undefined && args.limit !== null) {
      this.limit = args.limit;
    }
  }
};
UsageService_getUsageByRank_args.prototype = {};
UsageService_getUsageByRank_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size82 = 0;
        var _rtmp386;
        this.skus = [];
        var _etype85 = 0;
        _rtmp386 = input.readListBegin();
        _etype85 = _rtmp386.etype;
        _size82 = _rtmp386.size;
        for (var _i87 = 0; _i87 < _size82; ++_i87)
        {
          var elem88 = null;
          elem88 = input.readI32();
          this.skus.push(elem88);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.skuRank = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.isDescend = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.minVaue = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I64) {
        this.maxValue = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.fromTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I32) {
        this.toTs = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.I32) {
        this.interval = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.I32) {
        this.offset = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.I32) {
        this.limit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByRank_args.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByRank_args');
  if (this.skus !== null && this.skus !== undefined) {
    output.writeFieldBegin('skus', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.skus.length);
    for (var iter89 in this.skus)
    {
      if (this.skus.hasOwnProperty(iter89))
      {
        iter89 = this.skus[iter89];
        output.writeI32(iter89);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.skuRank !== null && this.skuRank !== undefined) {
    output.writeFieldBegin('skuRank', Thrift.Type.I32, 2);
    output.writeI32(this.skuRank);
    output.writeFieldEnd();
  }
  if (this.isDescend !== null && this.isDescend !== undefined) {
    output.writeFieldBegin('isDescend', Thrift.Type.BOOL, 3);
    output.writeBool(this.isDescend);
    output.writeFieldEnd();
  }
  if (this.minVaue !== null && this.minVaue !== undefined) {
    output.writeFieldBegin('minVaue', Thrift.Type.I64, 4);
    output.writeI64(this.minVaue);
    output.writeFieldEnd();
  }
  if (this.maxValue !== null && this.maxValue !== undefined) {
    output.writeFieldBegin('maxValue', Thrift.Type.I64, 5);
    output.writeI64(this.maxValue);
    output.writeFieldEnd();
  }
  if (this.fromTs !== null && this.fromTs !== undefined) {
    output.writeFieldBegin('fromTs', Thrift.Type.I32, 6);
    output.writeI32(this.fromTs);
    output.writeFieldEnd();
  }
  if (this.toTs !== null && this.toTs !== undefined) {
    output.writeFieldBegin('toTs', Thrift.Type.I32, 7);
    output.writeI32(this.toTs);
    output.writeFieldEnd();
  }
  if (this.interval !== null && this.interval !== undefined) {
    output.writeFieldBegin('interval', Thrift.Type.I32, 8);
    output.writeI32(this.interval);
    output.writeFieldEnd();
  }
  if (this.offset !== null && this.offset !== undefined) {
    output.writeFieldBegin('offset', Thrift.Type.I32, 9);
    output.writeI32(this.offset);
    output.writeFieldEnd();
  }
  if (this.limit !== null && this.limit !== undefined) {
    output.writeFieldBegin('limit', Thrift.Type.I32, 10);
    output.writeI32(this.limit);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageService_getUsageByRank_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.Pagination(args.success);
    }
  }
};
UsageService_getUsageByRank_result.prototype = {};
UsageService_getUsageByRank_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Pagination();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UsageService_getUsageByRank_result.prototype.write = function(output) {
  output.writeStructBegin('UsageService_getUsageByRank_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UsageServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
UsageServiceClient.prototype = {};
UsageServiceClient.prototype.seqid = function() { return this._seqid; };
UsageServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
UsageServiceClient.prototype.ping = function(str, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping(str);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping(str);
  }
};

UsageServiceClient.prototype.send_ping = function(str) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var params = {
    str: str
  };
  var args = new UsageService_ping_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UsageServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UsageService_ping_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ping failed: unknown result');
};
UsageServiceClient.prototype.getUsageByVendor = function(vid, skus, fromTs, toTs, interval, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getUsageByVendor(vid, skus, fromTs, toTs, interval);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getUsageByVendor(vid, skus, fromTs, toTs, interval);
  }
};

UsageServiceClient.prototype.send_getUsageByVendor = function(vid, skus, fromTs, toTs, interval) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getUsageByVendor', Thrift.MessageType.CALL, this.seqid());
  var params = {
    vid: vid,
    skus: skus,
    fromTs: fromTs,
    toTs: toTs,
    interval: interval
  };
  var args = new UsageService_getUsageByVendor_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UsageServiceClient.prototype.recv_getUsageByVendor = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UsageService_getUsageByVendor_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getUsageByVendor failed: unknown result');
};
UsageServiceClient.prototype.getUsageByVendorList = function(vids, skus, fromTs, toTs, interval, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getUsageByVendorList(vids, skus, fromTs, toTs, interval);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getUsageByVendorList(vids, skus, fromTs, toTs, interval);
  }
};

UsageServiceClient.prototype.send_getUsageByVendorList = function(vids, skus, fromTs, toTs, interval) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getUsageByVendorList', Thrift.MessageType.CALL, this.seqid());
  var params = {
    vids: vids,
    skus: skus,
    fromTs: fromTs,
    toTs: toTs,
    interval: interval
  };
  var args = new UsageService_getUsageByVendorList_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UsageServiceClient.prototype.recv_getUsageByVendorList = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UsageService_getUsageByVendorList_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getUsageByVendorList failed: unknown result');
};
UsageServiceClient.prototype.getUsageByGroup = function(vids, skus, fromTs, toTs, interval, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getUsageByGroup(vids, skus, fromTs, toTs, interval);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getUsageByGroup(vids, skus, fromTs, toTs, interval);
  }
};

UsageServiceClient.prototype.send_getUsageByGroup = function(vids, skus, fromTs, toTs, interval) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getUsageByGroup', Thrift.MessageType.CALL, this.seqid());
  var params = {
    vids: vids,
    skus: skus,
    fromTs: fromTs,
    toTs: toTs,
    interval: interval
  };
  var args = new UsageService_getUsageByGroup_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UsageServiceClient.prototype.recv_getUsageByGroup = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UsageService_getUsageByGroup_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getUsageByGroup failed: unknown result');
};
UsageServiceClient.prototype.getUsageByRank = function(skus, skuRank, isDescend, minVaue, maxValue, fromTs, toTs, interval, offset, limit, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getUsageByRank(skus, skuRank, isDescend, minVaue, maxValue, fromTs, toTs, interval, offset, limit);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getUsageByRank(skus, skuRank, isDescend, minVaue, maxValue, fromTs, toTs, interval, offset, limit);
  }
};

UsageServiceClient.prototype.send_getUsageByRank = function(skus, skuRank, isDescend, minVaue, maxValue, fromTs, toTs, interval, offset, limit) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getUsageByRank', Thrift.MessageType.CALL, this.seqid());
  var params = {
    skus: skus,
    skuRank: skuRank,
    isDescend: isDescend,
    minVaue: minVaue,
    maxValue: maxValue,
    fromTs: fromTs,
    toTs: toTs,
    interval: interval,
    offset: offset,
    limit: limit
  };
  var args = new UsageService_getUsageByRank_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

UsageServiceClient.prototype.recv_getUsageByRank = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UsageService_getUsageByRank_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getUsageByRank failed: unknown result');
};
var UsageServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
UsageServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
UsageServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new UsageService_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 1) {
    Q.fcall(this._handler.ping.bind(this._handler), args.str)
      .then(function(result) {
        var result_obj = new UsageService_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping(args.str, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UsageService_ping_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
UsageServiceProcessor.prototype.process_getUsageByVendor = function(seqid, input, output) {
  var args = new UsageService_getUsageByVendor_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getUsageByVendor.length === 5) {
    Q.fcall(this._handler.getUsageByVendor.bind(this._handler), args.vid, args.skus, args.fromTs, args.toTs, args.interval)
      .then(function(result) {
        var result_obj = new UsageService_getUsageByVendor_result({success: result});
        output.writeMessageBegin("getUsageByVendor", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByVendor", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getUsageByVendor(args.vid, args.skus, args.fromTs, args.toTs, args.interval, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UsageService_getUsageByVendor_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getUsageByVendor", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByVendor", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
UsageServiceProcessor.prototype.process_getUsageByVendorList = function(seqid, input, output) {
  var args = new UsageService_getUsageByVendorList_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getUsageByVendorList.length === 5) {
    Q.fcall(this._handler.getUsageByVendorList.bind(this._handler), args.vids, args.skus, args.fromTs, args.toTs, args.interval)
      .then(function(result) {
        var result_obj = new UsageService_getUsageByVendorList_result({success: result});
        output.writeMessageBegin("getUsageByVendorList", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByVendorList", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getUsageByVendorList(args.vids, args.skus, args.fromTs, args.toTs, args.interval, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UsageService_getUsageByVendorList_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getUsageByVendorList", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByVendorList", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
UsageServiceProcessor.prototype.process_getUsageByGroup = function(seqid, input, output) {
  var args = new UsageService_getUsageByGroup_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getUsageByGroup.length === 5) {
    Q.fcall(this._handler.getUsageByGroup.bind(this._handler), args.vids, args.skus, args.fromTs, args.toTs, args.interval)
      .then(function(result) {
        var result_obj = new UsageService_getUsageByGroup_result({success: result});
        output.writeMessageBegin("getUsageByGroup", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByGroup", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getUsageByGroup(args.vids, args.skus, args.fromTs, args.toTs, args.interval, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UsageService_getUsageByGroup_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getUsageByGroup", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByGroup", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
UsageServiceProcessor.prototype.process_getUsageByRank = function(seqid, input, output) {
  var args = new UsageService_getUsageByRank_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getUsageByRank.length === 10) {
    Q.fcall(this._handler.getUsageByRank.bind(this._handler), args.skus, args.skuRank, args.isDescend, args.minVaue, args.maxValue, args.fromTs, args.toTs, args.interval, args.offset, args.limit)
      .then(function(result) {
        var result_obj = new UsageService_getUsageByRank_result({success: result});
        output.writeMessageBegin("getUsageByRank", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByRank", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getUsageByRank(args.skus, args.skuRank, args.isDescend, args.minVaue, args.maxValue, args.fromTs, args.toTs, args.interval, args.offset, args.limit, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UsageService_getUsageByRank_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getUsageByRank", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUsageByRank", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
